apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: mysqlcompositesv2.catalog.cluster.local
spec:
  group: catalog.cluster.local
  metadata:
    labels:
      catalog.cluster.local/kind: MySQL
    annotations:
      catalog.cluster.local/title: "MySQLV2"
      catalog.cluster.local/description: "Unmanaged MySQL instance running within the cluster."

      catalog.cluster.local/maintainer: ""
      catalog.cluster.local/url: "https://www.mysql.com/"
      catalog.cluster.local/tags: "database,unmanaged,helm"
  names:
    kind: MySQLCompositeV2
    plural: mysqlcompositesv2
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: MySQL is a relational database management system (RDBMS) developed by Oracle that is based on structured query language (SQL). A database is a structured collection of data. It may be anything from a simple shopping list to a picture gallery or a place to hold the vast amounts of information in a corporate network.
          type: object
          properties:
            spec:
              type: object
              properties:
                crossplane:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                parameters:
                  type: object
                  properties:
                    size:
                      type: string
                      default: "8Gi"
                      pattern: ^(?<size>\d+(Ki|Mi|Gi|Ti|Pi|Ei|k|M|G|T|P|E)?)$
                    version:
                      type: string
                      default: "8"
                      description: "MySQL Major Version"
                      enum:
                        - "8"
