# Composition Definition: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.15.0
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kafkasv2.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v1
    kind: KafkaCompositeV2

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: kafka
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $kind := .observed.composite.resource.kind }}
            {{ $xrName := .observed.composite.resource.metadata.name }}
            {{ $namespace := .observed.composite.resource.metadata.namespace }}

            {{ $params := .observed.composite.resource.spec.parameters }}

            {{ $size := $params.size | default "8Gi" }}

            {{ $versionMapping := dict "3" "28.3.0" }}
            {{ $specVersion := $params.version | default "3" }}
            {{ $version := index $versionMapping $specVersion }}

            apiVersion: helm.m.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: {{ $xrName }}
              namespace: {{ $namespace }}
              annotations:
                crossplane.io/external-name: {{ $xrName }}
                gotemplating.fn.crossplane.io/composition-resource-name: "helm-release"
            spec:
              providerConfigRef:
                kind: ClusterProviderConfig
                name: provider-helm
              forProvider:
                chart: # https://artifacthub.io/packages/helm/bitnami/kafka
                  name: kafka
                  repository: oci://registry-1.docker.io/bitnamicharts
                  version: {{ $version }}
                namespace: {{ $namespace }}
                values:
                  fullnameOverride: {{ $xrName }}
                  commonLabels:
                    catalog.cluster.local/kind: {{ $kind }}
                    catalog.cluster.local/name: {{ $xrName }}
                  sasl:
                    client:
                      users:
                        - user
                  controller:
                    persistence:
                      size: {{ $size }}
                    replicaCount: 1
                  broker:
                    persistence:
                      size: {{ $size }}
                  # metrics:
                  #   enabled: true
                  #   kafka:
                  #     enabled: true
                  #   serviceMonitor:
                  #     enabled: true
                  extraConfig: |-
                    offsets.topic.replication.factor=1
                    transaction.state.log.replication.factor=1

              connectionDetails:
                - apiVersion: v1
                  kind: Secret
                  name: {{ $xrName }}-user-passwords
                  namespace: {{ $namespace }}
                  fieldPath: data.client-passwords
                  toConnectionSecretKey: password

                - apiVersion: v1
                  kind: Service
                  name: {{ $xrName }}
                  namespace: {{ $namespace }}
                  fieldPath: spec.ports[0].port
                  toConnectionSecretKey: port

              writeConnectionSecretToRef:
                name: {{ $xrName }}-connection
                namespace: {{ $namespace }}
            ---
            {{ $values := dig "resources" "helm-release" "resource" "spec" "forProvider" "values" dict .observed }}
            {{ $connectionDetails := dig "resources" "helm-release" "connectionDetails" dict .observed }}

            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              host: {{ printf "%s.%s" $xrName $namespace | b64enc }}
              username: {{ index $values.sasl.client.users 0 | b64enc }}
              password: {{ $connectionDetails.password }}
              port: {{ $connectionDetails.port }}
              saslmechanism: {{ "PLAIN" | b64enc }}
              securityprotocol: {{ "SASL_PLAINTEXT" | b64enc }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
