apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mongodbs-v2.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v2
    kind: MongoDB
  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: mongodb
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $xr := .observed.composite.resource }}
            {{ $kind := $xr.kind }}
            {{ $xrName := $xr.metadata.name }}
            {{ $namespace := $xr.metadata.namespace }}

            {{ $params := .observed.composite.resource.spec.parameters }}

            {{ $size := $params.size | default "8Gi" }}

            {{ $versionMapping := dict "8" "0.6.4" }}
            {{ $specVersion := $params.version | default "8" }}
            {{ $version := index $versionMapping $specVersion }}

            apiVersion: helm.m.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: {{ $xrName }}
              namespace: {{ $namespace }}
              annotations:
                crossplane.io/external-name: {{ $xrName }}
                gotemplating.fn.crossplane.io/composition-resource-name: "helm-release"
            spec:
              providerConfigRef:
                kind: ClusterProviderConfig
                name: provider-helm
              forProvider:
                chart:
                  name: mongodb
                  repository: oci://registry-1.docker.io/cloudpirates
                  version: {{ $version }}
                namespace: {{ $namespace }}
                values:
                  fullnameOverride: {{ $xrName  }}
                  commonLabels:
                    catalog.cluster.local/kind: {{ $kind }}
                    catalog.cluster.local/name: {{ $xrName }}
                  architecture: standalone
                  auth:
                    rootUser: root
                  persistence:
                    size: {{ $size }}
                  persistentVolumeClaimRetentionPolicy:
                    enabled: true
                    whenDeleted: Delete
                  # metrics:
                  #   enabled: true
                  #   serviceMonitor:
                  #     enabled: true

              connectionDetails:
                - apiVersion: v1
                  kind: Secret
                  name: {{ $xrName }}
                  namespace: {{ $namespace }}
                  fieldPath: data.mongodb-root-password
                  toConnectionSecretKey: password

                - apiVersion: v1
                  kind: Service
                  name: {{ $xrName }}
                  namespace: {{ $namespace }}
                  fieldPath: spec.ports[0].port
                  toConnectionSecretKey: port

              writeConnectionSecretToRef:
                name: {{ $xrName }}-connection-secret
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ $xrName }}-connection
              namespace: {{ $namespace }}
              annotations:
                {{ setResourceNameAnnotation "connection-secret" }}
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            {{- $helmSecret := (index $.observed.resources "helm-release").connectionDetails | default dict }}
            {{- if and $helmSecret.password $helmSecret.port }}
            data:
              host: {{ printf "%s.%s" $xrName $namespace | b64enc }}
              username: {{ dig "resources" "helm-release" "resource" "spec" "forProvider" "values" "auth" "rootUser" "root" .observed | b64enc }}
              password: {{ $helmSecret.password }}
              port: {{ $helmSecret.port }}
            {{- else }}
            data: {}
            {{- end }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
