apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: rabbitmqservercomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  connectionSecretKeys:
    - username
    - password
    - host
    - port
  names:
    kind: RabbitMQServerComposite
    plural: rabbitmqservercomposites
  claimNames:
    kind: RabbitMQServer
    plural: rabbitmqservers
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: RabbitMQ is a reliable and mature messaging and streaming broker.
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
            status:
              type: object
              properties: 
                credentials:
                  type: object
                  description: "Misuse composite status as temporary storage."
                  properties:
                    host:
                      type: string

                  