apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-helm
