apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: democomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  names:
    kind: DemoComposite
    plural: democomposites
  claimNames:
    kind: Demo
    plural: demos
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Demo is the Schema for the demos API
          type: object
          properties:
            status:
              description: DemoStatus defines the observed state of Demo
              type: object
              properties:
                credentials:
                  type: object
                  description: "Misuse composite status as temporary storage."
                  properties:
                    host:
                      type: string
