apiVersion: catalog.cluster.local/v1
kind: ElasticsearchCompositeV2
metadata:
  name: elasticsearch-sample
  namespace: crossplane-v2-migration-tests
spec:
  parameters:
    size: 1Gi
    version: "8"