apiVersion: catalog.cluster.local/v1
kind: PostgreSQLServer
metadata: 
  name: postgresqlserver-sample # why can't I rename this?
spec:
  size: 1Gi
  pvcRetentionWhenDeleted: Delete # Retain or Delete
  databaseName: sample
