# Composition Definition: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.15.0
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kafkas.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v1
    kind: KafkaComposite

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: kafka
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |

            {{ $claim := .observed.composite.resource.spec.claimRef }}

            {{ $versionMapping := dict "3" "28.3.0" }}
            {{ $version := index $versionMapping .observed.composite.resource.spec.version }}

            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              annotations:
                crossplane.io/external-name: {{ $claim.name }}
                gotemplating.fn.crossplane.io/composition-resource-name: "release"
            spec:
              providerConfigRef:
                name: provider-helm
              forProvider:
                chart: # https://artifacthub.io/packages/helm/bitnami/kafka
                  name: kafka
                  repository: oci://registry-1.docker.io/bitnamicharts
                  version: {{ $version }}
                namespace: {{ $claim.namespace }}
                values:
                  fullnameOverride: {{ $claim.name }}
                  commonLabels:
                    catalog.cluster.local/kind: {{ $claim.kind }}
                    catalog.cluster.local/name: {{ $claim.name }}
                  sasl:
                    client:
                      users:
                        - user
                  controller:
                    persistence:
                      size: 8Gi
                    replicaCount: 1
                  broker:
                    persistence:
                      size: {{ $.observed.composite.resource.spec.size}}
                  # metrics:
                  #   enabled: true
                  #   kafka:
                  #     enabled: true
                  #   serviceMonitor:
                  #     enabled: true
                  extraConfig: |-
                    offsets.topic.replication.factor=1
                    transaction.state.log.replication.factor=1

              connectionDetails:
                - apiVersion: v1
                  kind: Secret
                  name: {{ $claim.name }}-user-passwords
                  namespace: {{ $claim.namespace }}
                  fieldPath: data.client-passwords
                  toConnectionSecretKey: password

                - apiVersion: v1
                  kind: Service
                  name: {{ $claim.name }}
                  namespace: {{ $claim.namespace }}
                  fieldPath: spec.ports[0].port
                  toConnectionSecretKey: port

              writeConnectionSecretToRef:
                name: {{ $claim.name }}-connection
                namespace: {{ $claim.namespace }}
            ---
            {{ $values := .observed.resources.release.resource.spec.forProvider.values }}
            {{ $connectionDetails := .observed.resources.release.connectionDetails }}

            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              host: {{ printf "%s.%s" $claim.name $claim.namespace | b64enc }}
              username: {{ index $values.sasl.client.users 0 | b64enc }}
              password: {{ $connectionDetails.password }}
              port: {{ $connectionDetails.port }}
              saslmechanism: {{ "PLAIN" | b64enc }}
              securityprotocol: {{ "SASL_PLAINTEXT" | b64enc }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
