apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbcomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  names:
    kind: MariaDBComposite
    plural: mariadbcomposites
  claimNames:
    kind: MariaDB
    plural: mariadbs
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: MariaDB is a fast, scalable open-source community-supported relational database management system that's also an enhanced version of MySQL. Artturi Jalli is CEO and co-founder of Nodesk and founder of Codingem. MariaDB is fast, scalable and supports more storage engines than MySQL.
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                version:
                  type: string
                  enum:
                    - "11"
            status:
              type: object
              properties:
                credentials:
                  type: object
                  description: "Misuse composite status as temporary storage."
                  properties:
                    host:
                      type: string
