apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: redisservercomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  connectionSecretKeys: # is not needed, so maybe more harm than good, but could be useful for catalog UI or other tools like console?
    - password
    - host
    - port
  names:
    kind: RedisServerComposite
    plural: redisservercomposites
  claimNames:
    kind: RedisServer
    plural: redisservers
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: The open-source, in-memory data store used by millions of developers as a cache, vector database, document database, streaming engine, and message broker.
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
            status:
              type: object
              properties: 
                credentials:
                  type: object
                  description: "Misuse composite status as temporary storage."
                  properties:
                    host:
                      type: string

                  