apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mongodbs.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v1
    kind: MongoDBComposite

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: mangodb
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |

            {{ $claim := .observed.composite.resource.spec.claimRef }}

            {{ $versionMapping := dict "7" "15.5.1" "6" "13.16.2" }}
            {{ $version := index $versionMapping .observed.composite.resource.spec.version }}

            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              annotations:
                crossplane.io/external-name: {{ $claim.name }}
                gotemplating.fn.crossplane.io/composition-resource-name: "release"
            spec:
              providerConfigRef:
                name: provider-helm
              forProvider:
                chart: # https://artifacthub.io/packages/helm/bitnami/mongodb
                  name: mongodb
                  repository: oci://registry-1.docker.io/bitnamicharts
                  version: {{ $version }}
                namespace: {{ $claim.namespace }}
                values:
                  fullnameOverride: {{ $claim.name }}
                  commonLabels:
                    catalog.cluster.local/kind: {{ $claim.kind }}
                    catalog.cluster.local/name: {{ $claim.name }}
                  architecture: standalone
                  auth:
                    rootUser: root
                  persistence:
                    size: {{ $.observed.composite.resource.spec.size}}
                  persistentVolumeClaimRetentionPolicy:
                    enabled: true
                    whenDeleted: Delete
                  # metrics:
                  #   enabled: true
                  #   serviceMonitor:
                  #     enabled: true

              connectionDetails:
                - apiVersion: v1
                  kind: Secret
                  name: {{ $claim.name }}
                  namespace: {{ $claim.namespace }}
                  fieldPath: data.mongodb-root-password
                  toConnectionSecretKey: password

                - apiVersion: v1
                  kind: Service
                  name: {{ $claim.name }}
                  namespace: {{ $claim.namespace }}
                  fieldPath: spec.ports[0].port
                  toConnectionSecretKey: port

              writeConnectionSecretToRef:
                name: {{ $claim.name }}-connection
                namespace: {{ $claim.namespace }}
            ---
            {{ $values := .observed.resources.release.resource.spec.forProvider.values }}
            {{ $connectionDetails := .observed.resources.release.connectionDetails }}

            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              host: {{ printf "%s.%s" $claim.name $claim.namespace | b64enc }}
              username: {{ $values.auth.rootUser | b64enc }}
              password: {{ $connectionDetails.password }}
              port: {{ $connectionDetails.port }}
            {{ end }}