apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mongodbcomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  names:
    kind: MongoDBComposite
    plural: mongodbcomposites
  claimNames:
    kind: MongoDB
    plural: mongodbs
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: MongoDB is the Schema for the mongodbs API
          type: object
          properties:
            spec:
              description: MongoDBSpec defines the desired state of MongoDB
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                version:
                  type: string
                  enum:
                    - "6"
                    - "7"
            status:
              type: object
              properties:
                credentials:
                  type: object
                  description: "Missuse composite status as temporary storage."
                  properties:
                    host:
                      type: string
