apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mongodbcomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  metadata:
    labels:
      catalog.cluster.local/kind: MongoDB
    annotations:
      catalog.cluster.local/title: "MongoDB"
      catalog.cluster.local/description: "MongoDB is a popular NoSQL database that provides a flexible and scalable solution for storing and retrieving data. It is designed to handle large amounts of unstructured data, making it suitable for a wide range of applications."
      catalog.cluster.local/icon: "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTE1LjkuMDg3bC44NTQgMS42MDRjLjE5Mi4yOTYuNC41NTguNjQ1LjgwMi43MTUuNzE1IDEuMzk0IDEuNDY0IDIuMDA0IDIuMjY2IDEuNDQ3IDEuOSAyLjQyMyA0LjAxIDMuMTIgNi4yOTIuNDE4IDEuMzk0LjY0NSAyLjgyNC42NjIgNC4yNy4wNyA0LjMyMy0xLjQxMiA4LjAzNS00LjQgMTEuMTItLjQ4OC40ODgtMS4wMS45NC0xLjU3IDEuMzQyLS4yOTYgMC0uNDM2LS4yMjctLjU1OC0uNDM2LS4yMjctLjM4My0uMzY2LS44Mi0uNDM2LTEuMjU1LS4xMDUtLjUyMy0uMTc0LTEuMDQ2LS4xNC0xLjU4NnYtLjI0NEMxNi4wNTcgMjQuMjEgMTUuNzk2LjIxIDE1LjkuMDg3eiIgZmlsbD0iIzU5OTYzNiIvPgo8cGF0aCBkPSJNMTUuOS4wMzRjLS4wMzUtLjA3LS4wNy0uMDE3LS4xMDUuMDE3LjAxNy4zNS0uMTA1LjY2Mi0uMjk2Ljk2LS4yMS4yOTYtLjQ4OC41MjMtLjc2Ny43NjctMS41NSAxLjM0Mi0yLjc3IDIuOTYzLTMuNzQ3IDQuNzc2LTEuMyAyLjQ0LTEuOTcgNS4wNTUtMi4xNiA3LjgwOC0uMDg3Ljk5My4zMTQgNC40OTcuNjI3IDUuNTA4Ljg1NCAyLjY4NCAyLjM4OCA0LjkzMyA0LjM3NSA2Ljg4NS40ODguNDcgMS4wMS45MDYgMS41NSAxLjMyNS4xNTcgMCAuMTc0LS4xNC4yMS0uMjQ0YTQuNzggNC43OCAwIDAgMCAuMTU3LS42OGwuMzUtMi42MTRMMTUuOS4wMzR6IiBmaWxsPSIjNmNhYzQ4Ii8+CjxwYXRoIGQ9Ik0xNi43NTQgMjguODQ1Yy4wMzUtLjQuMjI3LS43MzIuNDM2LTEuMDYzLS4yMS0uMDg3LS4zNjYtLjI2LS40ODgtLjQ1My0uMTA1LS4xNzQtLjE5Mi0uMzgzLS4yNi0uNTc1LS4yNDQtLjczMi0uMjk2LTEuNS0uMzY2LTIuMjQ4di0uNDUzYy0uMDg3LjA3LS4xMDUuNjYyLS4xMDUuNzVhMTcuMzcgMTcuMzcgMCAwIDEtLjMxNCAyLjM1M2MtLjA1Mi4zMTQtLjA4Ny42MjctLjI4LjkwNiAwIC4wMzUgMCAuMDcuMDE3LjEyMi4zMTQuOTI0LjQgMS44NjUuNDUzIDIuODI0di4zNWMwIC40MTgtLjAxNy4zMy4zMy40Ny4xNC4wNTIuMjk2LjA3LjQzNi4xNzQuMTA1IDAgLjEyMi0uMDg3LjEyMi0uMTU3bC0uMDUyLS41NzV2LTEuNjA0Yy0uMDE3LS4yOC4wMzUtLjU1OC4wNy0uODJ6IiBmaWxsPSIjYzJiZmJmIi8+Cjwvc3ZnPgo="
      catalog.cluster.local/maintainer: ""
      catalog.cluster.local/url: "https://www.mongodb.com"
      catalog.cluster.local/tags: "database,unmanaged,helm"
  names:
    kind: MongoDBComposite
    plural: mongodbcomposites
  claimNames:
    kind: MongoDB
    plural: mongodbs
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: MongoDB is the Schema for the mongodbs API
          type: object
          properties:
            spec:
              description: MongoDBSpec defines the desired state of MongoDB
              type: object
              properties:
                size:
                  type: string
                  default: "8Gi"
                  pattern: ^(?P<size>\d+(Ki|Mi|Gi|Ti|Pi|Ei|k|M|G|T|P|E)?)$
                version:
                  type: string
                  default: "7"
                  description: MongoDB Major Version
                  enum:
                    - "6"
                    - "7"
