# Composition Definition: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.15.0
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dagsters-next.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v2
    kind: DagsterCompositeNext

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: get-environment-configs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: environment

    - step: dagster
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $kind := .observed.composite.resource.kind }}
            {{ $xrName := .observed.composite.resource.metadata.name }}
            {{ $namespace := .observed.composite.resource.metadata.namespace }}

            {{ $params := .observed.composite.resource.spec.parameters }}

            {{ $host := regexReplaceAll "[^a-z0-9-]" ($xrName | lower) "" }}
            {{ $zone := index $.context "apiextensions.crossplane.io/environment" "zone" }}

            apiVersion: helm.m.crossplane.io/v1beta1
            kind: Release # full example, see: https://github.com/crossplane-contrib/provider-helm/blob/master/examples/sample/release.yaml
            metadata:
              name: {{ $xrName }}
              namespace: {{ $namespace }}
              annotations:
                crossplane.io/external-name: {{ $xrName }}
                gotemplating.fn.crossplane.io/composition-resource-name: "helm-release"
            spec:
              providerConfigRef:
                kind: ClusterProviderConfig
                name: provider-helm
              forProvider:
                chart:
                  name: dagster
                  repository: https://dagster-io.github.io/helm
                  version: 1.12.3
                namespace: {{ $namespace }}
                values:
                  fullnameOverride: {{ $xrName }}
                  dagsterWebserver:
                    labels:
                      catalog.cluster.local/kind: {{ $kind }}
                      catalog.cluster.local/name: {{ $xrName }}
                  dagsterDaemon:
                    labels:
                      catalog.cluster.local/kind: {{ $kind }}
                      catalog.cluster.local/name: {{ $xrName }}
                  ingress:
                    labels:
                      catalog.cluster.local/kind: {{ $kind }}
                      catalog.cluster.local/name: {{ $xrName }}
                    enabled: true
                    {{- if or ($params.ingress.public) (eq $params.ingress nil) }}
                    ingressClassName: nginx
                    {{- else }}
                    ingressClassName: nginx-internal
                    {{- end }}
                    annotations:
                      kubernetes.io/tls-acme: "true"
                      nginx.ingress.kubernetes.io/auth-type: basic
                      nginx.ingress.kubernetes.io/auth-secret: {{ $xrName }}-auth
                      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
                    dagsterWebserver:
                      host: {{ $host }}.{{ $zone }}
                      path: /
                      pathType: Prefix
                      tls:
                        enabled: true
                        secretName: {{ $xrName }}-tls
                  telemetry:
                    enabled: false
            ---
            {{ $username := "admin" }}
            {{ $password := dig "resources" "secret" "resource" "stringData" "password" (randAlphaNum 12) .observed }}

            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ $xrName }}-auth
              namespace: {{ $namespace }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: "secret"
              labels:
                catalog.cluster.local/kind: {{ $kind }}
                catalog.cluster.local/name: {{ $xrName }}
                app.kubernetes.io/name: dagster
                app.kubernetes.io/instance: {{ $xrName }}
            stringData:
              username: {{ $username }}
              password: {{ $password }}
              auth: {{ htpasswd $username $password }}
            ---
            {{ $values := dig "resources" "helm-release" "resource" "spec" "forProvider" "values" dict .observed }}

            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ $xrName }}-connection
              namespace: {{ $namespace }}
              annotations:
                {{ setResourceNameAnnotation "connection-secret" }}
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              host: {{ printf "%s.%s" $host $zone | b64enc }}
              username: {{ $username | b64enc }}
              password: {{ $password | b64enc }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
