apiVersion: catalog.cluster.local/v1
kind: PostgreSQLCompositeV2
metadata:
  name: my-postgres-instance
  namespace: crossplane-v2-migration-tests
spec:
  parameters:
    size: "8Gi"
    version: "18"
