apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mongodbservercomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  names:
    kind: MongoDBServerComposite
    plural: mongodbservercomposites
  claimNames:
    kind: MongoDBServer
    plural: mongodbservers
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: MongoDBServer is the Schema for the mongodbservers API
          type: object
          properties:
            spec:
              description: MongoDBServerSpec defines the desired state of MongoDBServer
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
            status:
              type: object
              properties:
                credentials:
                  type: object
                  description: "Missuse composite status as temporary storage."
                  properties:
                    host:
                      type: string
