apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: elasticsearchservercomposites.catalog.cluster.local
spec:
  group: catalog.cluster.local
  names:
    kind: ElasticsearchServerComposite
    plural: elasticsearchservercomposites
  claimNames:
    kind: ElasticsearchServer
    plural: elasticsearchservers
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: ElasticsearchServer is the Schema for the elasticsearchservers API
          type: object
          properties:
            spec:
              description: ElasticsearchServerSpec defines the desired state of ElasticsearchServer
              type: object
              properties:
                size:
                  type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                version:
                  type: string
                  enum:
                    - "8"
            status:
              description: ElasticsearchServerStatus defines the observed state of ElasticsearchServer
              type: object
              properties:
                credentials:
                  type: object
                  description: "Misuse composite status as temporary storage."
                  properties:
                    host:
                      type: string
