apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-cluster-admin
  namespace: crossplane-system
subjects:
  - kind: ServiceAccount
    name: provider-helm
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: postgresqlservercomposites-access
# rules:
# - apiGroups:
#   - catalog.cluster.local
#   # resources:
#   # - postgresqlservercomposites
#   verbs:
#   - get
#   - list
#   - watch
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: crossplane-postgresqlservercomposites-access
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: postgresqlservercomposites-access
# subjects:
#   - kind: ServiceAccount
#     name: crossplane
#     namespace: crossplane-system