apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-helm
  # deploymentTemplate:
  #   spec:
  #     selector: {}
  #     template:
  #       spec:
  #         containers:
  #           - name: package-runtime
  #             args:
  #               - --enable-external-secret-stores # not available
# ---
# apiVersion: pkg.crossplane.io/v1alpha1
# kind: ControllerConfig
# metadata:
#   name: provider-helm
# spec:
#   args:
#     - --enable-external-secret-stores # not available, and probably the deprecated way how to do it