apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azureopenais.catalog.cluster.local
  annotations:
    catalog.cluster.local/title: "Azure OpenAI"
    catalog.cluster.local/description: "Azure OpenAi Services are a set of AI services that enable you to build AI solutions for any scenario and run them on any device."
    catalog.cluster.local/icon: "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iODAwcHgiIGhlaWdodD0iODAwcHgiIGZpbGw9IiMxN0E1ODMiIHJvbGU9ImltZyIgdmlld0JveD0iMCAwIDI0IDI0IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cGF0aCBkPSJNMjIuMjgxOSA5LjgyMTFhNS45ODQ3IDUuOTg0NyAwIDAgMC0uNTE1Ny00LjkxMDggNi4wNDYyIDYuMDQ2MiAwIDAgMC02LjUwOTgtMi45QTYuMDY1MSA2LjA2NTEgMCAwIDAgNC45ODA3IDQuMTgxOGE1Ljk4NDcgNS45ODQ3IDAgMCAwLTMuOTk3NyAyLjkgNi4wNDYyIDYuMDQ2MiAwIDAgMCAuNzQyNyA3LjA5NjYgNS45OCA1Ljk4IDAgMCAwIC41MTEgNC45MTA3IDYuMDUxIDYuMDUxIDAgMCAwIDYuNTE0NiAyLjkwMDFBNS45ODQ3IDUuOTg0NyAwIDAgMCAxMy4yNTk5IDI0YTYuMDU1NyA2LjA1NTcgMCAwIDAgNS43NzE4LTQuMjA1OCA1Ljk4OTQgNS45ODk0IDAgMCAwIDMuOTk3Ny0yLjkwMDEgNi4wNTU3IDYuMDU1NyAwIDAgMC0uNzQ3NS03LjA3Mjl6bS05LjAyMiAxMi42MDgxYTQuNDc1NSA0LjQ3NTUgMCAwIDEtMi44NzY0LTEuMDQwOGwuMTQxOS0uMDgwNCA0Ljc3ODMtMi43NTgyYS43OTQ4Ljc5NDggMCAwIDAgLjM5MjctLjY4MTN2LTYuNzM2OWwyLjAyIDEuMTY4NmEuMDcxLjA3MSAwIDAgMSAuMDM4LjA1MnY1LjU4MjZhNC41MDQgNC41MDQgMCAwIDEtNC40OTQ1IDQuNDk0NHptLTkuNjYwNy00LjEyNTRhNC40NzA4IDQuNDcwOCAwIDAgMS0uNTM0Ni0zLjAxMzdsLjE0Mi4wODUyIDQuNzgzIDIuNzU4MmEuNzcxMi43NzEyIDAgMCAwIC43ODA2IDBsNS44NDI4LTMuMzY4NXYyLjMzMjRhLjA4MDQuMDgwNCAwIDAgMS0uMDMzMi4wNjE1TDkuNzQgMTkuOTUwMmE0LjQ5OTIgNC40OTkyIDAgMCAxLTYuMTQwOC0xLjY0NjR6TTIuMzQwOCA3Ljg5NTZhNC40ODUgNC40ODUgMCAwIDEgMi4zNjU1LTEuOTcyOFYxMS42YS43NjY0Ljc2NjQgMCAwIDAgLjM4NzkuNjc2NWw1LjgxNDQgMy4zNTQzLTIuMDIwMSAxLjE2ODVhLjA3NTcuMDc1NyAwIDAgMS0uMDcxIDBsLTQuODMwMy0yLjc4NjVBNC41MDQgNC41MDQgMCAwIDEgMi4zNDA4IDcuODcyem0xNi41OTYzIDMuODU1OEwxMy4xMDM4IDguMzY0IDE1LjExOTIgNy4yYS4wNzU3LjA3NTcgMCAwIDEgLjA3MSAwbDQuODMwMyAyLjc5MTNhNC40OTQ0IDQuNDk0NCAwIDAgMS0uNjc2NSA4LjEwNDJ2LTUuNjc3MmEuNzkuNzkgMCAwIDAtLjQwNy0uNjY3em0yLjAxMDctMy4wMjMxbC0uMTQyLS4wODUyLTQuNzczNS0yLjc4MThhLjc3NTkuNzc1OSAwIDAgMC0uNzg1NCAwTDkuNDA5IDkuMjI5N1Y2Ljg5NzRhLjA2NjIuMDY2MiAwIDAgMSAuMDI4NC0uMDYxNWw0LjgzMDMtMi43ODY2YTQuNDk5MiA0LjQ5OTIgMCAwIDEgNi42ODAyIDQuNjZ6TTguMzA2NSAxMi44NjNsLTIuMDItMS4xNjM4YS4wODA0LjA4MDQgMCAwIDEtLjAzOC0uMDU2N1Y2LjA3NDJhNC40OTkyIDQuNDk5MiAwIDAgMSA3LjM3NTctMy40NTM3bC0uMTQyLjA4MDVMOC43MDQgNS40NTlhLjc5NDguNzk0OCAwIDAgMC0uMzkyNy42ODEzem0xLjA5NzYtMi4zNjU0bDIuNjAyLTEuNDk5OCAyLjYwNjkgMS40OTk4djIuOTk5NGwtMi41OTc0IDEuNDk5Ny0yLjYwNjctMS40OTk3WiIvPgo8L3N2Zz4="
    catalog.cluster.local/maintainer: ""
    catalog.cluster.local/url: "https://azure.microsoft.com/products/ai-services/openai-service"
    catalog.cluster.local/tags: "ai,ml,unmanaged"
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v1
    kind: AzureOpenAIComposite

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: get-environment-configs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: azure-environment

    - step: azure-openai
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: cognitiveservices.azure.upbound.io/v1beta1
            kind: Account
            metadata:
              name: {{ $.observed.composite.resource.spec.claimRef.name }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: account
            {{ if eq $.observed.composite.resource.spec.claimRef nil }}
                crossplane.io/external-name: {}
            {{ else }}
                crossplane.io/external-name: {{ regexReplaceAll "[^a-z0-9]" (printf "%s" $.observed.composite.resource.metadata.uid | lower) ""  | trunc 24 }}
            {{ end }}
            spec:
              forProvider:
                resourceGroupName: {{ index $.context "apiextensions.crossplane.io/environment" "resourcegroup" }}
                location: {{ default "Switzerland North" $.observed.composite.resource.spec.location }}               # called Region in Azure UI
                kind: OpenAI
                skuName: S0
              writeConnectionSecretToRef:
                namespace: {{ $.observed.composite.resource.spec.claimRef.namespace }}
                name: {{ $.observed.composite.resource.spec.claimRef.name }}-connection

            ---
            apiVersion: cognitiveservices.azure.upbound.io/v1beta1
            kind: Deployment
            metadata:
              name: {{ $.observed.composite.resource.spec.claimRef.name }}-gpt-4-turbo
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: deploymentgpt
                crossplane.io/external-name: gpt-4-turbo
            spec:
              forProvider:
                cognitiveAccountId: {{ $.observed.resources.account.resource.status.atProvider.id }}
                model:        
                  - format: OpenAI
                    name: gpt-4
                    version: turbo-2024-04-09
                scale:
                  - type: Standard
                    capacity: 10

            ---
            apiVersion: cognitiveservices.azure.upbound.io/v1beta1
            kind: Deployment
            metadata:
              name: {{ $.observed.composite.resource.spec.claimRef.name }}-embedding-ada-002
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: deploymentada
                crossplane.io/external-name: embedding-ada-002
            spec:
              forProvider:
                cognitiveAccountId: {{ $.observed.resources.account.resource.status.atProvider.id }}
                model:        
                  - format: OpenAI
                    name: text-embedding-ada-002
                    version: "2"
                scale:
                  - type: Standard
                    capacity: 10

            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              password: {{ index $.observed.resources.account.connectionDetails "attribute.primary_access_key" }}
              host: {{ $.observed.resources.account.resource.status.atProvider.endpoint | b64enc }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready

    - step: enforce-creation-sequence
      functionRef:
        name: crossplane-contrib-function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - "account"
            - "deploymentgpt"
          - sequence:
            - "account"
            - "deploymentada"
