apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-catalog
spec:
  crossplane:
    version: ">=v2.3.1 <v3.0.0"
  dependsOn:
    - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
      version: ">=v1.2.0"
    - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
      version: ">=v1.2.1"
    - provider: xpkg.upbound.io/upbound/provider-azure-storage
      version: ">=v2.0.0"
    - provider: xpkg.upbound.io/upbound/provider-azure-network
      version: ">=v2.0.0"
    - provider: xpkg.upbound.io/upbound/provider-azure-cognitiveservices
      version: ">=v2.0.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-go-templating
      version: ">=v0.11.4"
    - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: ">=v0.6.1"
    - function: xpkg.crossplane.io/crossplane-contrib/function-environment-configs
      version: ">=v0.6.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-sequencer
      version: ">=v0.5.0"
