apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-catalog
spec:
  crossplane:
    version: ">=v1.15.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.16.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.11.4"
    - provider: xpkg.upbound.io/upbound/provider-azure-storage
      version: ">=v1.1.0"
    - provider: xpkg.upbound.io/upbound/provider-azure-network
      version: ">=v1.1.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.4.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.4.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-environment-configs
      version: ">=v0.0.7"
    - function: xpkg.upbound.io/crossplane-contrib/function-sequencer
      version: ">=v0.1.2"
